
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: estein92@forcs.com
    password: vhtldptm3024
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true